Repository utk-cs/team-minsky, pull requests merged in 2018-12, with the labels that each got.

#93 Overhaul user experience
  dist/github/github_issue.js.map
  dist/main/minskylink.js
  dist/main/minskylink.js.map
  lib/main/minskylink.ts
  styles/style.less
Labels: CSS, atom, review, triggers-publish, ui

#92 Backend for GitHub Pull Requests
  dist/git-interface/comment.js
  dist/git-interface/comment.js.map
  dist/git-interface/commit.js
  dist/git-interface/commit.js.map
  dist/git-interface/file.js
  dist/git-interface/file.js.map
  dist/git-interface/issue.js
  dist/git-interface/issue.js.map
  dist/git-interface/pull_request.js
  dist/git-interface/pull_request.js.map
  dist/git-interface/review.js
  dist/git-interface/review.js.map
  dist/git-interface/user.js
  dist/git-interface/user.js.map
  dist/github/github_issue.js
  dist/github/github_issue.js.map
  dist/github/github_pr.js
  dist/github/github_pr.js.map
  lib/git-interface/comment.ts
  lib/git-interface/commit.ts
  lib/git-interface/file.ts
  lib/git-interface/issue.ts
  lib/git-interface/pull_request.ts
  lib/git-interface/review.ts
  lib/git-interface/user.ts
  lib/github/github_issue.ts
  lib/github/github_pr.ts
Labels: review, typescript

#94 user options mean real things
  dist/main/minskylink.js
  dist/main/minskylink.js.map
  lib/main/minskylink.ts
  package.json
Labels: atom, review, settings, triggers-publish
