Repository utk-cs/team-minsky, pull requests merged in 2018-10, with the labels that each got.

#35 Should solve issue 32.
  package.json
Labels: atom, meta-project, publishing, review, triggers-publish

#44 Example code being compiled and loading in Atom
  dist/client/dostuff.js
  dist/client/dostuff.js.map
  dist/main/minskylink.js
  dist/main/minskylink.js.map
  lib/client/dostuff.ts
  lib/main/minskylink.ts
  package-lock.json
  package.json
Labels: atom, packaging, review, typescript

#43 Rexissue42
  keymaps/team-minsky.json
  menues/team-minsky.json
Labels: atom, review

#49 Add @types/node for TS
  package-lock.json
  package.json
Labels: review, typescript

#48 Super README.md
  README.md
Labels: docs, publishing, review, triggers-publish

#36 Octowrapper
  .travis.yml
  README.md
  dist/git-interface/comment.js
  dist/git-interface/comment.js.map
  dist/git-interface/label.js
  dist/git-interface/label.js.map
  dist/git-interface/milestone.js
  dist/git-interface/milestone.js.map
  dist/git-interface/review.js
  dist/git-interface/review.js.map
  dist/git-interface/user.js
  dist/git-interface/user.js.map
  lib/client/dostuff.ts
  lib/git-interface/comment.ts
  lib/git-interface/issue.d.ts
  lib/git-interface/label.ts
  lib/git-interface/milestone.ts
  lib/git-interface/pull_request.d.ts
  lib/git-interface/review.ts
  lib/git-interface/user.ts
  lib/main/minskylink.ts
  lib/tsconfig.json
  package.json
  scripts/prettier.ts
Labels: review, typescript

#50 Linting
  lib/tslint.json
Labels: ci, review, typescript

#53 Rex Issues
  lib/main/minskylink.ts
  package.json
Labels: atom, learning, review

#57 Fix the issue tag finder to use a Layer and avoid duplication
  dist/main/minskylink.js
  dist/main/minskylink.js.map
  lib/main/minskylink.ts
  styles/style.less
Labels: atom, bug, review, triggers-publish

#59 GitHub wrapper
  dist/.gitkeep
  dist/git-interface/comment.js
  dist/git-interface/comment.js.map
  dist/git-interface/issue.js
  dist/git-interface/issue.js.map
  dist/git-interface/label.js
  dist/git-interface/label.js.map
  dist/git-interface/milestone.js
  dist/git-interface/milestone.js.map
  dist/git-interface/pull_request.js
  dist/git-interface/pull_request.js.map
  dist/git-interface/review.js
  dist/git-interface/review.js.map
  dist/github/github_issue.js
  dist/github/github_issue.js.map
  dist/github/test.js
  dist/github/test.js.map
  dist/main/minskylink.js
  dist/main/minskylink.js.map
  lib/git-interface/comment.ts
  lib/git-interface/issue.d.ts
  lib/git-interface/issue.ts
  lib/git-interface/label.ts
  lib/git-interface/milestone.ts
  lib/git-interface/pull_request.d.ts
  lib/git-interface/pull_request.ts
  lib/git-interface/review.ts
  lib/github/github_issue.ts
  lib/github/test.ts
  lib/main/minskylink.ts
  lib/tslint.json
Labels: review, typescript

#61 Framework function for opening issue under text cursor
  dist/main/minskylink.js
  dist/main/minskylink.js.map
  lib/main/minskylink.ts
Labels: CSS, HTML, atom, internals, review, ui

#64 Update GitHub Issue Comment Stuff
  .travis.yml
  dist/github/github_issue.js
  dist/github/github_issue.js.map
  lib/github/github_issue.ts
  package-lock.json
  package.json
Labels: review, typescript

#65 Adds a function to get Organization and Repo names for the current file
  .travis.yml
  lib/github/get_names.ts
  package.json
Labels: review, typescript

#67 Issue ID fix
  dist/github/get_names.js
  dist/github/get_names.js.map
  dist/github/github_issue.js
  dist/github/github_issue.js.map
  dist/github/test.js
  dist/github/test.js.map
  dist/main/minskylink.js.map
  lib/git-interface/issue.ts
  lib/github/github_issue.ts
  lib/github/test.ts
Labels: bug, review, typescript
