Repository utk-cs/team-minsky, pull requests merged in 2018-09, with the labels that each got.

#20 Add a package and some readme edits
  README.md
  package-lock.json
  package.json
Labels: meta-project, review, typescript

#23 Removes submodules.md because it's now in the wiki.
  submodules.md
Labels: docs, review

#24 Scaffolding TS plugin compilation
  dist/.gitkeep
  lib/tsconfig.json
  lib/tslint.json
  package-lock.json
  package.json
  scripts/prettier.ts
  scripts/tsconfig.json
Labels: help wanted, packaging, review, typescript

#25 Adds the MPL-2.0 license
  LICENSE.txt
  README.md
Labels: docs, legal, meta-project, publishing, review

#31 Enables the settings view in our package
  package-lock.json
  package.json
Labels: review, settings, triggers-publish

#34 Additional settings
  package.json
Labels: atom, in progress, review, settings
